
# This file is a part of Simple-XX/SimpleKernel
# (https://github.com/Simple-XX/SimpleKernel).
#
# workflow.yml for Simple-XX/SimpleKernel.

name: build

on:
  - push
  - pull_request
  - release

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build_docs:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --fix-missing -y doxygen graphviz clang-format clang-tidy cppcheck qemu-system lcov gdb-multiarch
          sudo apt install --fix-missing -y gcc g++ gcc-riscv64-linux-gnu g++-riscv64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build
        run: |
          cmake --preset=build_x86_64 
          cmake --build build_x86_64 --target doc

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/doc/html

  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --fix-missing -y doxygen graphviz clang-format clang-tidy cppcheck qemu-system lcov gdb-multiarch
          sudo apt install --fix-missing -y gcc g++ gcc-riscv64-linux-gnu g++-riscv64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: x86_64
        run: |
          cmake --preset=build_x86_64 
          # @todo ci 暂时跑不过
          #          cmake --build build_x86_64 --target boot
          #          cmake --build build_x86_64 --target kernel
          cmake --build build_x86_64 --target coverage

      - name: riscv64
        run: |
          cmake --preset=build_riscv64
          # @todo ci 暂时跑不过
      #          cmake --build build_riscv64 --target kernel

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: build_x86_64/coverage/coverage.info
          verbose: true
